# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ALX Higher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env: 
      TOKEN: ${{ secrets.TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.2"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pycodestyle pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with PYCODESTYLE
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pycodestyle *.py --count --select=E9,F63,F7,F82 --format pylint --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pycodestyle *.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
